/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Exam = IDL.Record({
  'subject' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'classLevel' : IDL.Nat,
});
export const Notice = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
});
export const Student = IDL.Record({
  'house' : IDL.Text,
  'name' : IDL.Text,
  'rollNumber' : IDL.Nat,
  'classLevel' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addExam' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addStudent' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'getAllExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
  'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Exam = IDL.Record({
    'subject' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'classLevel' : IDL.Nat,
  });
  const Notice = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
  });
  const Student = IDL.Record({
    'house' : IDL.Text,
    'name' : IDL.Text,
    'rollNumber' : IDL.Nat,
    'classLevel' : IDL.Nat,
  });
  
  return IDL.Service({
    'addExam' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addStudent' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'getAllExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
    'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };